### ISSUE TITLE
Start channel setting in case less than 1024.

### ISSUE THREAD

**Issue by Michi-123** [Tetratrio/stylegan2_pytorch#14]
Why do you set channel from 32 for 512x512 images?
```
# Here is an example training config file for 512x512 images.
channels: [32, 64, 128, 256, 512, 512, 512, 512]
```
Or in case 256 , starts from 64
`--channels 64 128 256 256 256 256 256`
Does the model converge faster than standard:  [4, 8, 16, ...]?

**Comment by adriansahlman** [comment]
Hey!
As I did not have enough GPU memory to train on 1024x1024 I had to use 512x512 instead. What I did if I remember correctly is that I took the number of channels of each layer that the paper used in their 1024x1024 model and just removed the final layer. Thats how I ended up with the channels in the example.

The paper mentions that they hypothesized that the final layer in the previous version of style-GAN has a capacity problem when using 16 channels, which is why they doubled it to 32.

I am guessing that using too many channels may reduce training stability and using too few may reduce output fidelity. However, this is just an assumption and I have not tested it.

If you have the time or computational resources you can try different values for the channels and see if it affects results.

The choice for number of channels is mentioned in section 4.2 of the [paper](https://arxiv.org/pdf/1912.04958.pdf#section.4)

**Comment by Michi-123** [comment]
Thank you. I trained with this parameter fot 256x256 images : 
`python run_training.py  --channels 4 8 16 32 64 128 256`
but model did not converge at checkpoint 5000 〜 16000.
Is this setting wrong?
 I don't know why you don't start from channel 4.

**Comment by adriansahlman** [comment]
I would say that convolutional layer with only 4 channels is a bit too small. Just to clarify, "channels" is the number of convolutional filters in the layer. In the paper they found that the layer with the least amount of channels (16) was too small and inhibited the model from reaching higher fidelity. They doubled that size to 32 instead and found that it worked better. So I would guess you should start with 32. Maybe `--channels 32 64 128 256 512 512 512`. Or since your images are of size 256x256 you dont need 512 channels for some layers. `--channels 32 64 128 128 128 128 128` or `--channels 32 64 128 256 256 256 256`.

Hope this helps!

**Comment by Michi-123** [comment]
I see! Thank you very much!
