### ISSUE TITLE
Do this repo completely reproduce the effect of the official StyleGAN2?

### ISSUE THREAD

**Issue by gsygsy96** [Tetratrio/stylegan2_pytorch#6]
Thanks for your efforts! Thank you @Tetratrio.  I plan to take it as a tool for image editing. Here I want to know whether this repo reproduces all details of official stylegan2. Are there some changes from the official one?

**Comment by adriansahlman** [comment]
Hey! No problem, glad people find is useful.

Now it was half a year ago I wrote this but as far as I can remember I spent a lot of time going through the source code of the official stylegan 2 repo to replicate it as closely as possible. Although using Pytorch instead of Tensorflow will probably make a 100% replication impossible.

This framework does however contain some additional functionality not found in the official implementation. It can not only be used for 2D data (images), but also for 1D and 3D data. There is a bit more freedom for the architecture of the models as well (the architecture used in the official implementation is of course a configuration that you can use when creating a model).

You can download and run the model weights from the official implementation in this repo which gives the exact same result (for inference at least). This means that the model uses the weights in the same way as the official implementation's model.

The training code is harder to replicate but I think it should be as close as it can get.

**Comment by gsygsy96** [comment]
Wow! That's cool! Thanks for your work again!
